# 언어 및 jdk 버전
language: java
jdk:
  - openjdk11

# 푸시할 떄 검사가 수행되는 브랜치
branches:
  only:
    - master

# Travis CI 서버의 홈
# 디렉토리에 의존성을 캐싱하여 의존성을 반복 주입하지 않도록 개선 작업
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r spring-boot-webservice *
  - mkdir -p deploy
  - mv spring-boot-webservice.zip deploy/spring-boot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: freelec-springboot-build-dongkii  # S3 버킷
    edge: true
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로 설정
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - ydk0831@gmail.com

