# 언어 및 jdk 버전
language: java
jdk:
  - openjdk11

# 푸시할 떄 검사가 수행되는 브랜치
branches:
  only:
    - master

# Travis CI 서버의 홈
# 디렉토리에 의존성을 캐싱하여 의존성을 반복 주입하지 않도록 개선 작업
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - ydk0831@gmail.com